# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Include" -I"C:/Users/silam/AppData/Local/OpenModelica1270/include/omc/c" -I"C:/Users/silam/AppData/Local/OpenModelica1270/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=RefrigerationTrainer_ClosedLoopM1e -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=6 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Users/silam/AppData/Local/OpenModelica1270/lib//omc" -L"C:/Users/silam/AppData/Local/OpenModelica1270/lib" -Wl,--stack,16777216,-rpath,"C:/Users/silam/AppData/Local/OpenModelica1270/lib//omc" -L"C:/Users/silam/AppData/Local/OpenModelica1270/bin" -Wl,-rpath,"C:/Users/silam/AppData/Local/OpenModelica1270/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/silam/OneDrive/Documents/CONDENSING UNIT/modelica/RefrigerationTrainer"
MAINFILE=RefrigerationTrainer.ClosedLoopM1e.c
MAINOBJ=RefrigerationTrainer.ClosedLoopM1e.o
CFILES=RefrigerationTrainer.ClosedLoopM1e_functions.c RefrigerationTrainer.ClosedLoopM1e_records.c \
RefrigerationTrainer.ClosedLoopM1e_01exo.c RefrigerationTrainer.ClosedLoopM1e_02nls.c RefrigerationTrainer.ClosedLoopM1e_03lsy.c RefrigerationTrainer.ClosedLoopM1e_04set.c RefrigerationTrainer.ClosedLoopM1e_05evt.c RefrigerationTrainer.ClosedLoopM1e_06inz.c RefrigerationTrainer.ClosedLoopM1e_07dly.c \
RefrigerationTrainer.ClosedLoopM1e_08bnd.c RefrigerationTrainer.ClosedLoopM1e_09alg.c RefrigerationTrainer.ClosedLoopM1e_10asr.c RefrigerationTrainer.ClosedLoopM1e_11mix.c RefrigerationTrainer.ClosedLoopM1e_12jac.c RefrigerationTrainer.ClosedLoopM1e_13opt.c RefrigerationTrainer.ClosedLoopM1e_14lnz.c \
RefrigerationTrainer.ClosedLoopM1e_15syn.c RefrigerationTrainer.ClosedLoopM1e_16dae.c RefrigerationTrainer.ClosedLoopM1e_17inl.c RefrigerationTrainer.ClosedLoopM1e_18spd.c \
   RefrigerationTrainer.ClosedLoopM1e_06inz_part0.c\
   RefrigerationTrainer.ClosedLoopM1e_06inz_part1.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) RefrigerationTrainer.ClosedLoopM1e.makefile RefrigerationTrainer.ClosedLoopM1e_literals.h RefrigerationTrainer.ClosedLoopM1e_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that RefrigerationTrainer.ClosedLoopM1e_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) RefrigerationTrainer.ClosedLoopM1e_functions.h RefrigerationTrainer.ClosedLoopM1e_literals.h $(OFILES)
	$(CC) -I. -o RefrigerationTrainer.ClosedLoopM1e$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Users/silam/AppData/Local/OpenModelica1270/bin/" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib//omc" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib/" "-LC:/Users/silam/AppData/Roaming/.openmodelica/binaries/RefrigerationTrainer" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/mingw64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/ucrt64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/win64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library" -lExternalMediaLib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) RefrigerationTrainer.ClosedLoopM1e_functions.h RefrigerationTrainer.ClosedLoopM1e_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)  "-LC:/Users/silam/AppData/Local/OpenModelica1270/bin/" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib//omc" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib/" "-LC:/Users/silam/AppData/Roaming/.openmodelica/binaries/RefrigerationTrainer" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/mingw64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/ucrt64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/win64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library" -lExternalMediaLib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o RefrigerationTrainer.ClosedLoopM1e$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)  "-LC:/Users/silam/AppData/Local/OpenModelica1270/bin/" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib//omc" "-LC:/Users/silam/AppData/Local/OpenModelica1270/lib/" "-LC:/Users/silam/AppData/Roaming/.openmodelica/binaries/RefrigerationTrainer" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/mingw64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/ucrt64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library/win64" "-LC:/Users/silam/AppData/Roaming/.openmodelica/libraries/ExternalMedia 4.1.1/Resources/Library" -lExternalMediaLib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f RefrigerationTrainer.ClosedLoopM1e_records.o $(MAINOBJ)

bundle:
	@tar -cvf RefrigerationTrainer.ClosedLoopM1e_Files.tar $(GENERATEDFILES)