/* Simulation code for RefrigerationTrainer.ClosedLoopM1eCS generated by the OpenModelica Compiler OpenModelica v1.27.0 (64-bit). */
#if !defined(RefrigerationTrainer_ClosedLoopM1eCS__MODEL_H)
#define RefrigerationTrainer_ClosedLoopM1eCS__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "RefrigerationTrainer.ClosedLoopM1eCS_functions.h"

#define RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_index 0
#define RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_index 1
#define RefrigerationTrainer_ClosedLoopM1eCS_Med_setSat__p_index 2
#define RefrigerationTrainer_ClosedLoopM1eCS_Med_setState__ph_index 3
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_index 4
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_index 5
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_setSat__p_index 6
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_setState__pT_index 7
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_setState__ph_index 8
#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_setState__ps_index 9
#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_index 10
#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_index 11
#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_setSat__p_index 12
#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_setState__ph_index 13
#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState_index 14
#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_index 15
#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_index 16
#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_setSat__p_index 17
#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_setState__ph_index 18
#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState_index 19
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_index 20
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_density_index 21
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_density__pTX_index 22
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_setState__pT_index 23
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_setState__pTX_index 24
#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_setState__ph_index 25

extern void RefrigerationTrainer_ClosedLoopM1eCS_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void RefrigerationTrainer_ClosedLoopM1eCS_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void RefrigerationTrainer_ClosedLoopM1eCS_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void RefrigerationTrainer_ClosedLoopM1eCS_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_checkForAsserts(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* RefrigerationTrainer_ClosedLoopM1eCS_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* RefrigerationTrainer_ClosedLoopM1eCS_relationDescription(int i);
extern void RefrigerationTrainer_ClosedLoopM1eCS_function_initSample(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* RefrigerationTrainer_ClosedLoopM1eCS_linear_model_frame(void);
extern const char* RefrigerationTrainer_ClosedLoopM1eCS_linear_model_datarecovery_frame(void);
extern int RefrigerationTrainer_ClosedLoopM1eCS_mayer(DATA* data, modelica_real** res, short *);
extern int RefrigerationTrainer_ClosedLoopM1eCS_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int RefrigerationTrainer_ClosedLoopM1eCS_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int RefrigerationTrainer_ClosedLoopM1eCS_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int RefrigerationTrainer_ClosedLoopM1eCS_setInputData(DATA *data, const modelica_boolean file);
extern int RefrigerationTrainer_ClosedLoopM1eCS_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void RefrigerationTrainer_ClosedLoopM1eCS_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void RefrigerationTrainer_ClosedLoopM1eCS_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int RefrigerationTrainer_ClosedLoopM1eCS_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void RefrigerationTrainer_ClosedLoopM1eCS_read_simulation_info(SIMULATION_INFO* simulationData);
extern void RefrigerationTrainer_ClosedLoopM1eCS_read_input_fmu(MODEL_DATA* modelData);
extern void RefrigerationTrainer_ClosedLoopM1eCS_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_inputNames(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1eCS_dataReconciliationInputNames(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1eCS_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1eCS_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int RefrigerationTrainer_ClosedLoopM1eCS_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int RefrigerationTrainer_ClosedLoopM1eCS_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "RefrigerationTrainer.ClosedLoopM1eCS_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(RefrigerationTrainer_ClosedLoopM1eCS__MODEL_H) */


