/* Additional record code for RefrigerationTrainer.ClosedLoopM1eCS generated by the OpenModelica Compiler OpenModelica v1.27.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "RefrigerationTrainer.ClosedLoopM1eCS_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties__desc__fields[14] = {"Tsat","dTp","ddldp","ddvdp","dhldp","dhvdp","dl","dv","hl","hv","psat","sigma","sl","sv"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.Med.SaturationProperties", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* ths = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_ths);
  // ths->_Tsat has no default value.
  // ths->_dTp has no default value.
  // ths->_ddldp has no default value.
  // ths->_ddvdp has no default value.
  // ths->_dhldp has no default value.
  // ths->_dhvdp has no default value.
  // ths->_dl has no default value.
  // ths->_dv has no default value.
  // ths->_hl has no default value.
  // ths->_hv has no default value.
  // ths->_psat has no default value.
  // ths->_sigma has no default value.
  // ths->_sl has no default value.
  // ths->_sv has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_Tsat, modelica_real in_dTp, modelica_real in_ddldp, modelica_real in_ddvdp, modelica_real in_dhldp, modelica_real in_dhvdp, modelica_real in_dl, modelica_real in_dv, modelica_real in_hl, modelica_real in_hv, modelica_real in_psat, modelica_real in_sigma, modelica_real in_sl, modelica_real in_sv) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_dst);
  dst->_Tsat = in_Tsat;
  dst->_dTp = in_dTp;
  dst->_ddldp = in_ddldp;
  dst->_ddvdp = in_ddvdp;
  dst->_dhldp = in_dhldp;
  dst->_dhvdp = in_dhvdp;
  dst->_dl = in_dl;
  dst->_dv = in_dv;
  dst->_hl = in_hl;
  dst->_hv = in_hv;
  dst->_psat = in_psat;
  dst->_sigma = in_sigma;
  dst->_sl = in_sl;
  dst->_sv = in_sv;
}

void RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_external*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.Med.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_external*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_Med_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties__desc__fields[14] = {"Tsat","dTp","ddldp","ddvdp","dhldp","dhvdp","dl","dv","hl","hv","psat","sigma","sl","sv"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.comp.Medium.SaturationProperties", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* ths = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_ths);
  // ths->_Tsat has no default value.
  // ths->_dTp has no default value.
  // ths->_ddldp has no default value.
  // ths->_ddvdp has no default value.
  // ths->_dhldp has no default value.
  // ths->_dhvdp has no default value.
  // ths->_dl has no default value.
  // ths->_dv has no default value.
  // ths->_hl has no default value.
  // ths->_hv has no default value.
  // ths->_psat has no default value.
  // ths->_sigma has no default value.
  // ths->_sl has no default value.
  // ths->_sv has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_Tsat, modelica_real in_dTp, modelica_real in_ddldp, modelica_real in_ddvdp, modelica_real in_dhldp, modelica_real in_dhvdp, modelica_real in_dl, modelica_real in_dv, modelica_real in_hl, modelica_real in_hv, modelica_real in_psat, modelica_real in_sigma, modelica_real in_sl, modelica_real in_sv) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = in_Tsat;
  dst->_dTp = in_dTp;
  dst->_ddldp = in_ddldp;
  dst->_ddvdp = in_ddvdp;
  dst->_dhldp = in_dhldp;
  dst->_dhvdp = in_dhvdp;
  dst->_dl = in_dl;
  dst->_dv = in_dv;
  dst->_hl = in_hl;
  dst->_hv = in_hv;
  dst->_psat = in_psat;
  dst->_sigma = in_sigma;
  dst->_sl = in_sl;
  dst->_sv = in_sv;
}

void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_external*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties__desc__fields[14] = {"Tsat","dTp","ddldp","ddvdp","dhldp","dhvdp","dl","dv","hl","hv","psat","sigma","sl","sv"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.cond.Cells.Medium.SaturationProperties", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* ths = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_ths);
  // ths->_Tsat has no default value.
  // ths->_dTp has no default value.
  // ths->_ddldp has no default value.
  // ths->_ddvdp has no default value.
  // ths->_dhldp has no default value.
  // ths->_dhvdp has no default value.
  // ths->_dl has no default value.
  // ths->_dv has no default value.
  // ths->_hl has no default value.
  // ths->_hv has no default value.
  // ths->_psat has no default value.
  // ths->_sigma has no default value.
  // ths->_sl has no default value.
  // ths->_sv has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_Tsat, modelica_real in_dTp, modelica_real in_ddldp, modelica_real in_ddvdp, modelica_real in_dhldp, modelica_real in_dhvdp, modelica_real in_dl, modelica_real in_dv, modelica_real in_hl, modelica_real in_hv, modelica_real in_psat, modelica_real in_sigma, modelica_real in_sl, modelica_real in_sv) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = in_Tsat;
  dst->_dTp = in_dTp;
  dst->_ddldp = in_ddldp;
  dst->_ddvdp = in_ddvdp;
  dst->_dhldp = in_dhldp;
  dst->_dhvdp = in_dhvdp;
  dst->_dl = in_dl;
  dst->_dv = in_dv;
  dst->_hl = in_hl;
  dst->_hv = in_hv;
  dst->_psat = in_psat;
  dst->_sigma = in_sigma;
  dst->_sl = in_sl;
  dst->_sv = in_sv;
}

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_external*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties__desc__fields[14] = {"Tsat","dTp","ddldp","ddvdp","dhldp","dhvdp","dl","dv","hl","hv","psat","sigma","sl","sv"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.evap.Cells.Medium.SaturationProperties", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* ths = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_ths);
  // ths->_Tsat has no default value.
  // ths->_dTp has no default value.
  // ths->_ddldp has no default value.
  // ths->_ddvdp has no default value.
  // ths->_dhldp has no default value.
  // ths->_dhvdp has no default value.
  // ths->_dl has no default value.
  // ths->_dv has no default value.
  // ths->_hl has no default value.
  // ths->_hv has no default value.
  // ths->_psat has no default value.
  // ths->_sigma has no default value.
  // ths->_sl has no default value.
  // ths->_sv has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_Tsat, modelica_real in_dTp, modelica_real in_ddldp, modelica_real in_ddvdp, modelica_real in_dhldp, modelica_real in_dhvdp, modelica_real in_dl, modelica_real in_dv, modelica_real in_hl, modelica_real in_hv, modelica_real in_psat, modelica_real in_sigma, modelica_real in_sl, modelica_real in_sv) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = in_Tsat;
  dst->_dTp = in_dTp;
  dst->_ddldp = in_ddldp;
  dst->_ddvdp = in_ddvdp;
  dst->_dhldp = in_dhldp;
  dst->_dhvdp = in_dhvdp;
  dst->_dl = in_dl;
  dst->_dv = in_dv;
  dst->_hl = in_hl;
  dst->_hv = in_hv;
  dst->_psat = in_psat;
  dst->_sigma = in_sigma;
  dst->_sl = in_sl;
  dst->_sv = in_sv;
}

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_external*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_SaturationProperties*)(v_dst);
  dst->_Tsat = src->_Tsat;
  dst->_dTp = src->_dTp;
  dst->_ddldp = src->_ddldp;
  dst->_ddvdp = src->_ddvdp;
  dst->_dhldp = src->_dhldp;
  dst->_dhvdp = src->_dhvdp;
  dst->_dl = src->_dl;
  dst->_dv = src->_dv;
  dst->_hl = src->_hl;
  dst->_hv = src->_hv;
  dst->_psat = src->_psat;
  dst->_sigma = src->_sigma;
  dst->_sl = src->_sl;
  dst->_sv = src->_sv;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.comp.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_external*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_comp_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.cond.Cells.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_external*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.cond.Cells.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_cond_Cells_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}


#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.evap.Cells.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_external*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}

#define RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.evap.Cells.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_evap_Cells_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}


#define RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState__desc_added 1
const char* RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState__desc__fields[15] = {"T","a","beta","cp","cv","d","ddhp","ddph","eta","h","kappa","lambda","p","phase","s"};
struct record_description RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState__desc = {
  "RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState", /* package_record__X */
  "RefrigerationTrainer.ClosedLoopM1eCS.txv.Medium.ThermodynamicState", /* package.record_X */
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState__desc__fields
};

void RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* ths = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_ths);
  // ths->_T has no default value.
  // ths->_a has no default value.
  // ths->_beta has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_d has no default value.
  // ths->_ddhp has no default value.
  // ths->_ddph has no default value.
  // ths->_eta has no default value.
  // ths->_h has no default value.
  // ths->_kappa has no default value.
  // ths->_lambda has no default value.
  // ths->_p has no default value.
  // ths->_phase has no default value.
  // ths->_s has no default value.
}
void RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_T, modelica_real in_a, modelica_real in_beta, modelica_real in_cp, modelica_real in_cv, modelica_real in_d, modelica_real in_ddhp, modelica_real in_ddph, modelica_real in_eta, modelica_real in_h, modelica_real in_kappa, modelica_real in_lambda, modelica_real in_p, modelica_integer in_phase, modelica_real in_s) {
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_dst);
  dst->_T = in_T;
  dst->_a = in_a;
  dst->_beta = in_beta;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_d = in_d;
  dst->_ddhp = in_ddhp;
  dst->_ddph = in_ddph;
  dst->_eta = in_eta;
  dst->_h = in_h;
  dst->_kappa = in_kappa;
  dst->_lambda = in_lambda;
  dst->_p = in_p;
  dst->_phase = in_phase;
  dst->_s = in_s;
}

void RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_copy_to_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* src = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_external* dst = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_external*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}
void RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_copy_from_external_p(void* v_src, void* v_dst) {
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_external* src = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState_external*)(v_src);
  RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState* dst = (RefrigerationTrainer_ClosedLoopM1eCS_txv_Medium_ThermodynamicState*)(v_dst);
  dst->_T = src->_T;
  dst->_a = src->_a;
  dst->_beta = src->_beta;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_d = src->_d;
  dst->_ddhp = src->_ddhp;
  dst->_ddph = src->_ddph;
  dst->_eta = src->_eta;
  dst->_h = src->_h;
  dst->_kappa = src->_kappa;
  dst->_lambda = src->_lambda;
  dst->_p = src->_p;
  dst->_phase = src->_phase;
  dst->_s = src->_s;
}

#ifdef __cplusplus
}
#endif

