/* Simulation code for RefrigerationTrainer.ClosedLoopM1e generated by the OpenModelica Compiler OpenModelica v1.27.0 (64-bit). */
#if !defined(RefrigerationTrainer_ClosedLoopM1e__MODEL_H)
#define RefrigerationTrainer_ClosedLoopM1e__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "RefrigerationTrainer.ClosedLoopM1e_functions.h"

#define RefrigerationTrainer_ClosedLoopM1e_Med_SaturationProperties_index 0
#define RefrigerationTrainer_ClosedLoopM1e_Med_ThermodynamicState_index 1
#define RefrigerationTrainer_ClosedLoopM1e_Med_setSat__p_index 2
#define RefrigerationTrainer_ClosedLoopM1e_Med_setState__ph_index 3
#define RefrigerationTrainer_ClosedLoopM1e_comp_Medium_ThermodynamicState_index 4
#define RefrigerationTrainer_ClosedLoopM1e_comp_Medium_setState__pT_index 5
#define RefrigerationTrainer_ClosedLoopM1e_comp_Medium_setState__ph_index 6
#define RefrigerationTrainer_ClosedLoopM1e_comp_Medium_setState__ps_index 7
#define RefrigerationTrainer_ClosedLoopM1e_cond_Cells_Medium_SaturationProperties_index 8
#define RefrigerationTrainer_ClosedLoopM1e_cond_Cells_Medium_ThermodynamicState_index 9
#define RefrigerationTrainer_ClosedLoopM1e_cond_Cells_Medium_setSat__p_index 10
#define RefrigerationTrainer_ClosedLoopM1e_cond_Cells_Medium_setState__ph_index 11
#define RefrigerationTrainer_ClosedLoopM1e_cond_Cells_heatTransfer_Medium_ThermodynamicState_index 12
#define RefrigerationTrainer_ClosedLoopM1e_evap_Cells_Medium_SaturationProperties_index 13
#define RefrigerationTrainer_ClosedLoopM1e_evap_Cells_Medium_ThermodynamicState_index 14
#define RefrigerationTrainer_ClosedLoopM1e_evap_Cells_Medium_setSat__p_index 15
#define RefrigerationTrainer_ClosedLoopM1e_evap_Cells_Medium_setState__ph_index 16
#define RefrigerationTrainer_ClosedLoopM1e_evap_Cells_heatTransfer_Medium_ThermodynamicState_index 17
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_ThermodynamicState_index 18
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_density_index 19
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_density__pTX_index 20
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_setState__pT_index 21
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_setState__pTX_index 22
#define RefrigerationTrainer_ClosedLoopM1e_txv_Medium_setState__ph_index 23

extern void RefrigerationTrainer_ClosedLoopM1e_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void RefrigerationTrainer_ClosedLoopM1e_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void RefrigerationTrainer_ClosedLoopM1e_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int RefrigerationTrainer_ClosedLoopM1e_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_checkForAsserts(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int RefrigerationTrainer_ClosedLoopM1e_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* RefrigerationTrainer_ClosedLoopM1e_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* RefrigerationTrainer_ClosedLoopM1e_relationDescription(int i);
extern void RefrigerationTrainer_ClosedLoopM1e_function_initSample(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int RefrigerationTrainer_ClosedLoopM1e_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* RefrigerationTrainer_ClosedLoopM1e_linear_model_frame(void);
extern const char* RefrigerationTrainer_ClosedLoopM1e_linear_model_datarecovery_frame(void);
extern int RefrigerationTrainer_ClosedLoopM1e_mayer(DATA* data, modelica_real** res, short *);
extern int RefrigerationTrainer_ClosedLoopM1e_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int RefrigerationTrainer_ClosedLoopM1e_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int RefrigerationTrainer_ClosedLoopM1e_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int RefrigerationTrainer_ClosedLoopM1e_setInputData(DATA *data, const modelica_boolean file);
extern int RefrigerationTrainer_ClosedLoopM1e_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void RefrigerationTrainer_ClosedLoopM1e_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void RefrigerationTrainer_ClosedLoopM1e_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int RefrigerationTrainer_ClosedLoopM1e_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void RefrigerationTrainer_ClosedLoopM1e_read_simulation_info(SIMULATION_INFO* simulationData);
extern void RefrigerationTrainer_ClosedLoopM1e_read_input_fmu(MODEL_DATA* modelData);
extern void RefrigerationTrainer_ClosedLoopM1e_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_inputNames(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1e_dataReconciliationInputNames(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1e_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int RefrigerationTrainer_ClosedLoopM1e_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int RefrigerationTrainer_ClosedLoopM1e_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int RefrigerationTrainer_ClosedLoopM1e_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "RefrigerationTrainer.ClosedLoopM1e_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(RefrigerationTrainer_ClosedLoopM1e__MODEL_H) */


